import { Point } from '@pixi/core';
import { Sprite } from '@pixi/sprite';
import { get2dArray } from '@utils/get2dArray';
import { getDistance } from '@utils/getDistance';
import { isEqualPoint } from '@utils/isEqualPoint';

import { basicBfs } from './movement/MovementAlgorithm';
import { TILE_SIZE } from '../../constants';
import { EntityType } from '../../data/enums/EntityType';
import { textureTile, textureWall } from '../graphics/Graphics';

import type { Actor } from '../../types/Actor';
import type { Cell } from '../../types/Cell';
import type { PlayBoard } from '../../types/PlayBoard';
import type { WorldContainer } from '../../types/WorldContainer';

let freeTiles: Point[] = [];
let visibleTiles: Point[] = [];

export function getRandomFreeTilePoint(): Point {
  return freeTiles.splice(Math.floor(Math.random() * freeTiles.length), 1)[0] ?? new Point(0, 0);
}

// Convert map generated by WFC to playboard
export function convertToBoard(protoBoard: number[][]): PlayBoard {
  const width = protoBoard.length;
  const height = protoBoard[0].length;

  const resultBoard = get2dArray(width, height, {}) as PlayBoard;

  for (let x = 0; x < width; x += 1) {
    for (let y = 0; y < height; y += 1) {
      resultBoard[x][y] = {
        isGround: protoBoard[x][y] !== 0,
        entityType: EntityType.None,
        position: new Point(x, y),
        wasSeen: false,
        actor: null,
      } as Cell;
    }
  }

  freeTiles = resultBoard
    .flat()
    .filter((e) => e.isGround && !e.actor)
    .map((e) => e.position);

  // Select the exit tile
  const exitTilePoint = getRandomFreeTilePoint();
  const exitTile = resultBoard[exitTilePoint.x][exitTilePoint.y];

  exitTile.entityType = EntityType.Exit;

  return resultBoard;
}

export function tileBoard(world: WorldContainer) {
  for (const [x, cellRow] of world.board.entries()) {
    for (const [y, cell] of cellRow.entries()) {
      let newTileSprite;

      if (cell.isGround) {
        newTileSprite = new Sprite(textureTile);
      } else {
        newTileSprite = new Sprite(textureWall);
      }

      newTileSprite.width = TILE_SIZE;
      newTileSprite.height = TILE_SIZE;

      const newTile = world.addChild(newTileSprite);

      newTile.x = x * TILE_SIZE;
      newTile.y = y * TILE_SIZE;

      newTile.eventMode = 'none';
      newTile.visible = false;
      cell.sprite = newTile;
    }
  }
}

export function isPointVisible(point: Point) {
  return visibleTiles.some((e) => isEqualPoint(e, point));
}

// Update tiles visibility
// TODO: Factor in walls
export function updateTilesVisibility(player: Actor, playBoard: PlayBoard): PlayBoard {
  visibleTiles = basicBfs(playBoard, player.position, player.sightRange);

  return playBoard.map((e) => e.map((cell) => {
    const dist = getDistance(player.position, cell.position);

    if (isPointVisible(cell.position)) {
      cell.wasSeen = true;
      cell.sprite.visible = true;
      cell.sprite.alpha = 1;

      if (dist === 1 && cell.isGround) {
        cell.sprite.tint = 0xffff88;
        cell.sprite.eventMode = 'static';
      } else {
        cell.sprite.tint = 0xffffff;
        cell.sprite.eventMode = 'none';
      }
    } else if (cell.wasSeen) {
      cell.sprite.alpha = 0.5;
    } else {
      cell.sprite.visible = false;
    }

    return cell;
  }));
}
